// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using viageMais.Data;

#nullable disable

namespace viageMais.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240109210944_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("viageMais.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imgUrl");

                    b.Property<string>("MainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mainName");

                    b.HasKey("Id");

                    b.ToTable("destination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "foz-do-iguacu",
                            Country = "brasil",
                            Description = "Localizada na tríplice fronteira entre Brasil, Argentina e Paraguai, Foz do Iguaçu é conhecida pelas impressionantes Cataratas do Iguaçu. O Parque Nacional do Iguaçu abriga uma das maiores e mais espetaculares quedas d'água do mundo, oferecendo uma experiência única em meio à natureza exuberante da região.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/foziguacu.webp",
                            MainName = "foz-do-iguaçu"
                        },
                        new
                        {
                            Id = 2,
                            City = "caribe",
                            Country = "caribe",
                            Description = "O Caribe é uma região paradisíaca que abrange várias ilhas, como as Bahamas, Jamaica, Porto Rico e muitas outras. Conhecido por suas praias de areia branca, águas cristalinas e uma rica cultura vibrante, o Caribe é um destino popular para turistas em busca de relaxamento, esportes aquáticos e vida noturna animada.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/caribe.webp",
                            MainName = "caribe"
                        },
                        new
                        {
                            Id = 3,
                            City = "dubai",
                            Country = "emirados-árabes-unidos",
                            Description = "Dubai é uma metrópole futurista no coração do Oriente Médio, conhecida por suas arquiteturas icônicas, como o Burj Khalifa, o edifício mais alto do mundo. A cidade oferece uma mistura de modernidade e tradição, com shoppings luxuosos, resorts de classe mundial, desertos fascinantes e uma atmosfera cosmopolita.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/dubai.webp",
                            MainName = "dubai"
                        },
                        new
                        {
                            Id = 4,
                            City = "maceio",
                            Country = "brasil",
                            Description = "Capital do estado de Alagoas, Maceió é famosa por suas praias deslumbrantes e piscinas naturais formadas por recifes de corais. As águas calmas e cristalinas do litoral atraem visitantes em busca de paisagens tropicais, enquanto a cultura local e a gastronomia regional adicionam um toque especial à experiência.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/maceio.webp",
                            MainName = "maceió"
                        },
                        new
                        {
                            Id = 5,
                            City = "londres",
                            Country = "inglaterra",
                            Description = "A capital do Reino Unido, Londres, é uma cidade histórica e cosmopolita. Oferece uma rica herança cultural, incluindo ícones como o Palácio de Buckingham, o Parlamento, a Torre de Londres e o Museu Britânico. Além disso, a cidade é conhecida por suas opções de compras, teatros, parques e uma vibrante cena gastronômica.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/londres.webp",
                            MainName = "londres"
                        },
                        new
                        {
                            Id = 6,
                            City = "cancun",
                            Country = "méxico",
                            Description = "Situada na Península de Yucatán, Cancún é um destino de resort popular, conhecido por suas praias de areia branca e águas cristalinas do Caribe. Além de suas atrações naturais, Cancún oferece uma animada vida noturna, restaurantes de alta qualidade e a proximidade das antigas ruínas maias de Chichén Itzá.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/mexico.webp",
                            MainName = "cancún"
                        },
                        new
                        {
                            Id = 7,
                            City = "serra-gaucha",
                            Country = "brasil",
                            Description = "A Serra Gaúcha, no estado do Rio Grande do Sul, é uma região encantadora com forte influência da colonização italiana. Cidades como Gramado e Canela são famosas por sua arquitetura europeia, culinária deliciosa, chocolates artesanais e festivais de inverno. A região é um destino popular durante o Natal Luz, quando as cidades se iluminam com decorações festivas.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/serra-gaucha.jpg",
                            MainName = "serra-gaúcha"
                        },
                        new
                        {
                            Id = 8,
                            City = "machu-picchu",
                            Country = "peru",
                            Description = "Machu Picchu é uma antiga cidade inca situada nas montanhas dos Andes peruanos. Considerada uma das Sete Maravilhas do Mundo, esta cidade histórica é conhecida por sua arquitetura impressionante, terraços agrícolas e localização espetacular. Uma visita a Machu Picchu proporciona uma experiência única e mística.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/peru.webp",
                            MainName = "machu-picchu"
                        },
                        new
                        {
                            Id = 9,
                            City = "paris",
                            Country = "frança",
                            Description = "A Cidade Luz, Paris, é famosa por sua arquitetura clássica, museus renomados como o Louvre, a icônica Torre Eiffel e suas avenidas elegantes. Além disso, Paris é conhecida como um centro de moda, arte, gastronomia refinada e romance, tornando-a um destino popular para viajantes de todo o mundo.",
                            ImgUrl = "https://raw.githubusercontent.com/LeandroNcosta/ViageMais/main/images/parisjpg.jpg",
                            MainName = "paris"
                        });
                });

            modelBuilder.Entity("viageMais.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assessments")
                        .HasColumnType("int")
                        .HasColumnName("assessments");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imgUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.HasKey("Id");

                    b.ToTable("hotel");
                });
#pragma warning restore 612, 618
        }
    }
}
